---
title: "BJsales"
author: "Nishanth Girish"
date: "2023-06-20"
output: html_document
---

```{r}
# Plot time series 'BJsales'
ts.plot(BJsales)
```


```{r}
plot(diff(BJsales))
plot(diff(diff(BJsales)))
```


```{r}
pacf(diff(diff(BJsales)), lag.max= 25)
```
# Lag 1, Lag 2, Lag 3, Lag 10, Lag 19 are significant
Keeping parsimony principle in mind, the order of AR terms can be 0,1,2 or 3. 


```{r}
acf(diff(diff(BJsales)), lag.max= 25)
```

# Lag 1, Lag 8, Lag 11 are significant.
Keeping parsimony principle in mind, the order of MA term can be 0 or 1. 

```{r}
d=2
for(p in 1:4){
  for(q in 1:2){
        if(p+d+q<=6){
          model<-arima(x=BJsales, order = c((p-1),d,(q-1)))
          pval<-Box.test(model$residuals, lag=log(length(model$residuals)))
          sse<-sum(model$residuals^2)
          cat(p-1,d,q-1, 'AIC=', model$aic, ' SSE=',sse,' p-VALUE=', pval$p.value,'\n')
        }
      }
}
```

We fit ARIMA(0,2,1), and look at the time plot, ACF and PACF of the residuals.

```{r}
model<-arima(BJsales, order=c(0,2,1))

par(mfrow=c(2,2))

plot(model$residuals)
acf(model$residuals)
pacf(model$residuals)
qqnorm(model$residuals)
```
```{r}
Box.test(model$residuals, lag=log(length(model$residuals)), type = "Ljung")
```
p>0.05, fail to reject null hypothesis. 

```{r}
model
```


```{r}
forecast(model, h= 3)
```


```{r}
```


```{r}
```

